source ~/.bashrc
# eval "$(chef shell-init bash)"
#eval "$(chef shell-init bash)"

export CC=gcc-6
# export LDFLAGS=/usr/local/opt/openssl/lib
# export CPPFLAGS=/usr/local/opt/openssl/include
# export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
# export ARM_ARCH="arm64"
# export CFLAGS="-arch ${ARM_ARCH}"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
