#!/bin/bash

# source /usr/share/chruby/chruby.sh
for file in ~/.bash/*.bash; do
  source $file
done

# unset DISPLAY

# eval "$(fasd --init auto)"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/skylerl/Downloads/google-cloud-sdk/path.bash.inc' ]; then source '/home/skylerl/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/skylerl/Downloads/google-cloud-sdk/completion.bash.inc' ]; then source '/home/skylerl/Downloads/google-cloud-sdk/completion.bash.inc'; fi

# export LS_OPTIONS='--color=auto'
# eval "`dircolors`"
# alias ls='ls $LS_OPTIONS'
