source ~/.bashrc

export CC=gcc
# export LDFLAGS=/usr/local/opt/openssl/lib
# export CPPFLAGS=/usr/local/opt/openssl/include
# export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
# export ARM_ARCH="arm64"
# export CFLAGS="-arch ${ARM_ARCH}"

if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
  exec startx
  # source ~/.xinitrc
else
  SSH_ENV="$HOME/.ssh/environment"

  function start_agent {
      echo "Initialising new SSH agent..."
      /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
      echo succeeded
      chmod 600 "${SSH_ENV}"
      . "${SSH_ENV}" > /dev/null
      /usr/bin/ssh-add;
  }

  # Source SSH settings, if applicable

  if [ -f "${SSH_ENV}" ]; then
      . "${SSH_ENV}" > /dev/null
      #ps ${SSH_AGENT_PID} doesn't work under cywgin
      ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
          start_agent;
      }
  else
      start_agent;
  fi
fi

NPM_PACKAGES="${HOME}/.node_packages"

PATH="$NPM_PACKAGES/bin:$PATH"

export PATH="$HOME/.cargo/bin:$PATH"
source $HOME/.cargo/env

VBoxClient --clipboard || echo "VBoxClient clipboard"
